---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-gateway
  namespace: kube-system
spec:
  secretName: cilium-gateway
  commonName: hubble.home.svc
  dnsNames:
    - "hubble.home.svc"
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: themairs-production-ca-2022
