---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cilium-resources
  namespace: flux-system
spec:
  interval: 24h
  path: kubernetes/infrastructure/cilium/cilium/overlays/prod/resources
  prune: true
  dependsOn:
    - name: infrastructure-cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
...
