---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: kube-system
  labels:
    test: it
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: prod-tls-gw
  hostnames:
    - hubble.home.svc
  rules:
    - backendRefs:
        - name: hubble-ui
          port: 80
