---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-gateway
  namespace: default
spec:
  secretName: podinfo-gateway
  commonName: podinfo.home.svc
  dnsNames:
    - "podinfo.home.svc"
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: themairs-production-ca-2022
