---
apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: clusterdns
  annotations:
    io.cilium/lb-ipam-ips: 192.168.76.226
spec:
  selector:
    app: bind9
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  type: LoadBalancer
...
