---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-gateway
  namespace: linkding
spec:
  secretName: linkding-gateway
  commonName: linkding.home.svc
  dnsNames:
    - "linkding.home.svc"
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: themairs-production-ca-2022
