---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  targetNamespace: linkding
  releaseName: linkding
  interval: 12h

  chart:
    spec:
      chart: linkding
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
      interval: 12h
  values:
    persistentVolumeClaim:
      create: false

    env:
      - name: LD_SUPERUSER_NAME
        valueFrom:
          secretKeyRef:
            name: superuser
            key: username
      - name: LD_SUPERUSER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: superuser
            key: password
      - name: LD_DB_ENGINE
        value: postgres
      - name: LD_DB_HOST
        value: linkding-database-rw
      - name: LD_DB_USER
        valueFrom:
          secretKeyRef:
            name: linkding
            key: username
      - name: LD_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: linkding
            key: password
...