---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-database
  namespace: linkding
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi

  superuserSecret:
    name: postgres-superuser

  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding
