---
# namespace: redis has to be created manually
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database-operators
spec:
  targetNamespace: database-operators
  releaseName: cloudnative-pg
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.18.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  interval: 60m
...
