---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  targetNamespace: cert-manager
  releaseName: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: v1.13.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 30m

  install:
    crds: CreateReplace

  upgrade:
    crds: CreateReplace

  valuesFrom:
    - name: cert-manager-helm-chart-overrides
      kind: ConfigMap
...