---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cloudnative-pg
  namespace: flux-system
spec:
  interval: 24h
  path: kubernetes/infrastructure/database-operators/cloudnative-pg
  prune: true
  retryInterval: 5s
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
...
