---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-rook-ceph
  namespace: flux-system
spec:
  interval: 24h
  path: kubernetes/infrastructure/rook-ceph/rook-ceph
  prune: true
  retryInterval: 5s
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
...
