---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 24h
  path: kubernetes/infrastructure/rook-ceph/rook-ceph-cluster/overlays/prod
  prune: true
  dependsOn:
    - name: infrastructure-rook-ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
...
