---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-helm-chart-overrides
  namespace: cert-manager
data:
  values.yaml: |
    ingressShim:
      defaultIssuerName: "themairs-production-ca-2022"
      defaultIssuerKind: "ClusterIssuer"
    webhook:
      enabled: true
    installCRDs: true
    replicaCount: 1
...
