---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  targetNamespace: rook-ceph
  releaseName: rook-ceph
  interval: 60m

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  chart:
    spec:
      chart: rook-ceph
      version: v1.12.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 60m

  values:
    enableDiscoveryDaemon: true
...