---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-cluster
  namespace: rook-ceph
spec:
  releaseName: ceph-cluster
  targetNamespace: rook-ceph
  interval: 15m

  install:
    crds: Skip

  upgrade:
    crds: Skip

  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.12.7
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 120m

  valuesFrom:
    - kind: ConfigMap
      name: ceph-cluster-helm-overrides

...