---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-gateway
  namespace: rook-ceph
spec:
  secretName: ceph-gateway
  commonName: ceph.home.svc
  dnsNames:
    - "ceph.home.svc"
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: themairs-production-ca-2022
