---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-cluster-helm-overrides
  namespace: rook-ceph
data:
  values.yaml: |
    clusterName: ceph-cluster
    cephClusterSpec:
      mgr:
        rook:
          storage_class: ceph-filesystem
        modules:
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true
      storage:
        useAllDevices: false
        useAllNodes: false
        nodes:
          - name: talos-a1
            devices:
              - name: sdb
              - name: sdc
          - name: talos-a2
            devices:
              - name: sdb
              - name: sdc
          - name: talos-a3
            devices:
              - name: sdb
              - name: sdc
      dashboard:
        ssl: false
      resources:
        mgr:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "512Mi"
        mon:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "10m"
            memory: "512Mi"
        osd:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "10m"
            memory: "512Mi"
        mgr-sidecar:
          limits:
            cpu: "500m"
            memory: "100Mi"
          requests:
            cpu: "10m"
            memory: "40Mi"
        crashcollector:
          limits:
            cpu: "500m"
            memory: "60Mi"
          requests:
            cpu: "10m"
            memory: "60Mi"
        logcollector:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "100Mi"
        cleanup:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "100Mi"
        exporter:
          limits:
            cpu: "250m"
            memory: "128Mi"
          requests:
            cpu: "10m"
            memory: "50Mi"
