---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-csi-driver-nfs-storageclasses
  namespace: flux-system
spec:
  interval: 24h
  path: kubernetes/infrastructure/csi-driver-nfs/overlays/prod/storageclasses
  prune: true
  dependsOn:
    - name: infrastructure-csi-driver-nfs
  sourceRef:
    kind: GitRepository
    name: flux-system
  retryInterval: 5s
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
...
