users:
  - name: kubeadm
    gecos: Kubernetes Administrator
    primary_group: kubeadm
    groups:
      wheel
    sudo: ALL=(ALL) ALL
    lock_passwd: false
    password: $6$rounds=4096$mdTfSE3ok1guQ9/M$4iF2ZZxHQfKSlyxd6ZA04UXelYLfNFVf/ZarXwQapzmIHLG08yFUvaMQ3W9wbiVLq0zgIZ2eCZiliyzulTkwo0
    ssh_authorized_keys:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKR4eZKowtwGtkia6IFgasCybSf0VAvFR0IdYySePbTjY+4xUf0mpL43Q9Cwt2TXRRAER930BAho85z59eCplLE= bill.mair@pc

# ---------- Self-signed certificates ----------
#ca_certs:
#
#  trusted:
#  - |
#    -----BEGIN CERTIFICATE-----
#    . . . .
#    -----END CERTIFICATE-----
#  - |
#    -----BEGIN CERTIFICATE-----
#    . . . .
#    -----END CERTIFICATE-----

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent

