---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-dns
  namespace: flux-system
spec:
  interval: 24h
  path: kubernetes/infrastructure/clusterdns/external-dns/prod
  prune: true
  retryInterval: 5s
  dependsOn:
    - name: infrastructure-bind9
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
...
